explorer_docker_network_name: explorernet

beacon_explorer_container_name: explorer
execution_explorer_container_name: blockscout

explorer_memory: 9000m
beacon_explorer_image_name: "parithoshj/beacon-explorer:print-chain-id"
execution_explorer_image_name: "skylenet/blockscout:v4.0.0-beta"

explorer_first_block: 1
explorer_eth1_source_hostname: "merge-devnet-0-ethx-explorer-lighthouse-nethermind-1"
explorer_eth1_source_ip_address: "{{hostvars[explorer_eth1_source_hostname].ansible_host}}"
explorer_eth2_source_ip_address: "{{explorer_eth1_source_ip_address}}"

explorer_postgres_container_name: postgres
explorer_postgres_image_name: "postgres:12.0"
explorer_postgres_memory: 9000m
explorer_postgres_port: "5432"
explorer_postgres_ip: "172.1.1.100"
explorer_postgres_user: postgres

# Set in secrets.yaml
# explorer_postgres_password: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/merge-devnets/merge-devnet-3/explorer-postgres') }}"

explorer_postgres_host_dir: "{{home_dir}}/explorer_postgres_data"
explorer_postgres_volumes:
  - "{{explorer_postgres_host_dir}}:/postgresql/data"
explorer_postgres_start_args: "-i -h {{explorer_postgres_ip}}"

explorer_postgres_init_volumes:
  - "{{explorer_host_dir}}:/src"

explorer_postgres_init_args: >
  psql
  -f /src/tables.sql
  -d db
  -h {{explorer_postgres_ip}}
  -p {{explorer_postgres_port}}
  -U {{explorer_postgres_user}}

explorer_host_dir: "{{home_dir}}/explorer_data"

execution_explorer_genesis_host_path: "{{explorer_host_dir}}/genesis.json"
execution_explorer_genesis_cont_path: /data/genesis.json
execution_explorer_volumes:
  - "{{explorer_host_dir}}:/data"

beacon_explorer_config_host_path: "{{explorer_host_dir}}/eth2_config.yaml"
beacon_explorer_config_cont_path: /data/eth2_config.yaml
beacon_explorer_volumes:
  - "{{explorer_host_dir}}:/data"

beacon_explorer_start_args: "./explorer --config=/data/config.yaml"

execution_explorer_start_args: 'sh -c "echo $DATABASE_URL &&
  mix do ecto.create, ecto.migrate &&
  exec mix phx.server" '

explorer_stats_container_name: explorerstats

explorer_stats_volumes:
  - "{{explorer_host_dir}}:/data"

explorer_stats_start_args: "./statistics --config=/data/config.yaml"

explorer_beacon_extra_args: "--slots-per-archive-point=64"
